### ISSUE TITLE
Code for bug fixes / voice playback (request)

### ISSUE THREAD

**Issue by AJRubenstein** [cdb-boop/Space-Quest-V-Voice-Acting-Mod#2]
Hi there,

I just want to say how glad I am that you've actually re-upped this. The amount of work that has gone into this is staggering, and I really must commend it all. I'm also really sorry that there was such a negative reaction to it all.

I was wanting to humbly request if me and a couple of other curious folk would be able to see the script changes you've made to (what I'm assuming are the decompiled) SCI SQ5 scripts to enable the voice fixes and bug squashing? We've been noodling around with a fan voiced version of SQ5 for a while but haven't had a lot of success integrating voice playback into SQ5 as of yet. If you'd be willing to share your progress, you would obviously be gloriously celebrated for your efforts and completely credited for all of the hard work you've put in, and have our eternal gratitude for helping it happen.

I also COMPLETELY understand if you do not want to share the code. 

Please let me know! 

Thanks.

**Comment by cdb-boop** [comment]
You should be able to decompile it and then simply replace the vocals in SCI Companion. However, we can talk through email or something if you want me to share the changes. I know some others have uploaded decompiled games to GitHub, but I want to play it safe.

**Comment by AJRubenstein** [comment]
No worries. I'd prefer the uncompiled version just so we don't risk any decompilation artifacts. My email address is rubensteinvideo@gmail.com - would you be willing to throw a line my way so we can discuss further? 

Once again, really appreciate all of this.

**Comment by cdb-boop** [comment]
@AJRubenstein Sure. When I'm free later today I'll email you.

**Comment by Doomlazer** [comment]
I could facilitate adding voice to this project
